### ISSUE TITLE
IRC bot can't connect within Minecraft 1.18

### ISSUE THREAD

**Issue by jason-green-io** [pblop/twitch-chat#22]
using fabric loader 0.12.8
Fabric API 43.1+1.18
Minecraft 1.18
java 17

```
[19:21:11] [Render thread/INFO]: [CHAT] You won't connect to a channel because you haven't selected any. You can select a channel with /twitch watch [channel]
[19:21:11] [Render thread/INFO]: [STDERR]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[19:21:11] [Render thread/INFO]: [STDERR]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[19:21:11] [Render thread/INFO]: [STDERR]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[19:21:11] [Render thread/INFO]: [STDOUT]: TWITCH BOT STARTED
[19:21:11] [Render thread/INFO]: [CHAT] Connecting...
[19:21:11] [pool-7-thread-1/INFO]: [STDERR]: SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
[19:21:11] [pool-7-thread-1/INFO]: [STDERR]: SLF4J: Defaulting to no-operation MDCAdapter implementation.
[19:21:11] [pool-7-thread-1/INFO]: [STDERR]: SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
[19:21:11] [listenerPool0-thread1/INFO]: [STDOUT]: TWITCH DISCONNECT: DisconnectEvent(userChannelDaoSnapshot=org.pircbotx.snapshot.UserChannelDaoSnapshot@2128c5d, disconnectException=null)
[19:21:11] [pool-7-thread-1/ERROR]: Uncaught exception in thread "pool-7-thread-1"
java.lang.NoSuchFieldError: WHITESPACE
	at org.pircbotx.Utils.tokenizeLine(Utils.java:166) ~[org_pircbotx_pircbotx-2.1-9a3aa37a4ca5ecbf.jar:?]
	at org.pircbotx.PircBotX.sendRawLineToServer(PircBotX.java:368) ~[org_pircbotx_pircbotx-2.1-9a3aa37a4ca5ecbf.jar:?]
	at org.pircbotx.Utils.sendRawLineToServer(Utils.java:133) ~[org_pircbotx_pircbotx-2.1-9a3aa37a4ca5ecbf.jar:?]
	at org.pircbotx.output.OutputRaw.rawLineNow(OutputRaw.java:109) ~[org_pircbotx_pircbotx-2.1-9a3aa37a4ca5ecbf.jar:?]
	at org.pircbotx.output.OutputRaw.rawLineNow(OutputRaw.java:94) ~[org_pircbotx_pircbotx-2.1-9a3aa37a4ca5ecbf.jar:?]
	at org.pircbotx.output.OutputCAP.getSupported(OutputCAP.java:37) ~[org_pircbotx_pircbotx-2.1-9a3aa37a4ca5ecbf.jar:?]
	at org.pircbotx.PircBotX.connect(PircBotX.java:277) ~[org_pircbotx_pircbotx-2.1-9a3aa37a4ca5ecbf.jar:?]
	at org.pircbotx.PircBotX.startBot(PircBotX.java:177) ~[org_pircbotx_pircbotx-2.1-9a3aa37a4ca5ecbf.jar:?]
	at to.pabli.twitchchat.twitch_integration.Bot.lambda$start$0(Bot.java:70) ~[twitchchat-0.11.2b.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by pblop** [comment]
Fixed in d6d7cddd22e703ef12d1d7dee965bd65628f98be
