### ISSUE TITLE
Error crash version 1.17.1

### ISSUE THREAD

**Issue by MiClobiMC** [pblop/twitch-chat#26]
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install modmenu, any version.
Unmet dependency listing:
	 - Mod 'Twitch Chat Bridge' (twitchchat) 0.11.2b requires any version of modmenu, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install modmenu, any version.
Unmet dependency listing:
	 - Mod 'Twitch Chat Bridge' (twitchchat) 0.11.2b requires any version of modmenu, which is missing!
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more

**Comment by pblop** [comment]
Install modmenu
